name: deploy prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-release:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4
      - uses: pguyot/arm-runner-action@v2
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: prepare go
        run: |
          go clean
          go mod tidy
          go mod download
  
      - name: build
        run: go build ./cmd/lambda/api.go
  
    env:
      STAGE: prod
      # MONGO_URI: ${{ secrets.MONGO_URI }}
      # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
